// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Gwrpc_qDhVq92VwI8lWDY32o_Tc8qmg',
    appId: '1:797472053396:web:7e522aa523f3864225bc81',
    messagingSenderId: '797472053396',
    projectId: 'bookglance-a73c9',
    authDomain: 'bookglance-a73c9.firebaseapp.com',
    storageBucket: 'bookglance-a73c9.appspot.com',
    measurementId: 'G-L6DWQGDGQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADvNFbEggODbWhPjuTiNZAUvn3L4Pm-Bs',
    appId: '1:797472053396:android:073d48516a68338125bc81',
    messagingSenderId: '797472053396',
    projectId: 'bookglance-a73c9',
    storageBucket: 'bookglance-a73c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6W9i5M6t9X7xyTz5wF1UIzDHnQFhksl4',
    appId: '1:797472053396:ios:d5b0f29d3a6bd15a25bc81',
    messagingSenderId: '797472053396',
    projectId: 'bookglance-a73c9',
    storageBucket: 'bookglance-a73c9.appspot.com',
    iosClientId: '797472053396-ti8bgm45kec0gmrks1q86jd9qmp3dt4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookGlance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6W9i5M6t9X7xyTz5wF1UIzDHnQFhksl4',
    appId: '1:797472053396:ios:88436c7cd8cd5d0525bc81',
    messagingSenderId: '797472053396',
    projectId: 'bookglance-a73c9',
    storageBucket: 'bookglance-a73c9.appspot.com',
    iosClientId: '797472053396-2gqf72abmu2o5rqd8nrin6v3246aerck.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookGlance.RunnerTests',
  );
}
